### PR TITLE
External annotation sideloading

### PR DESCRIPTION
**Pull request by SJShaw**
Implements the proposed sideloading of external annotations as per #122.

**Input**
Input files are used by using the `--sideloader FILENAME` option. As each file can only have one tool specified, multiple files can be provided as `--sideloader FILENAME_A,FILENAME_B` to bundle multiple tools worth of annotations together into the antiSMASH result.

An example of a multi-record input with a variety of detail values is given in `antismash/detection/sideloader/test/data/good.json`. While only one each of subregion and protocluster is added in this example, as many as desired can be added.

The schema and subschemas are in `sideloader/schemas/general`. The loading functions can be used standalone (without the rest of antiSMASH) and are

**Output**
- Genbank: subregion and protocluster annotations are made with all provided area details, but only tool name, tool configuration is not currently included
- HTML: subregions and protoclusters are shown as per other areas of the same type, detail tabs are created for each area with all details of both the area and the tool configuration

**Potential issues:**
- sideloaded protoclusters will never quite function the same as detected protoclusters, without an additional section of specifying which CDS features are considered the defining CDS features (which then leads to a much more complex schema, as those CDS features need to have which profiles are mentioned, and so on)
- for sideloaded protoclusters to trigger specific analysis modules (like the t2pks module), the product names must match those in the `hmm_detection` rules exactly
- sideloaded subregions are never coloured, so telling multiple tools worth of inputs
- the `hmm_detection` module will always run, so multiple protocluster annotations of the same area can be created if the external annotations include a matching area
- protoclusters added that do not match an existing product will not have any colouring in the HTML output

The `antismash.js` used in this PR is also a prototype, before merging this would need to be updated to an actual release.

### CODE REVIEW

**Comment by SJShaw** [comment]
It occurred to me that if we want to support multiple versions of the schema, we might want to embed a version number into the sideloaded JSON. If we only want to support the latest or at most a backwards compatible latest, then it may not be neccessary.

**Comment by SJShaw** [comment]
Issues found using the DeepBGC example:
- subregion numeric identifiers in the region view reset to 1 in each JS-generated SVG, where the detail tabs keep the correct numbering
- regions with no protoclusters/`unknown` products don't have a contrast colour, so it's difficult to see by indicators which region is currently shown
- region labels overflow when the subregion is small, while it may cost a lot of vertical space, the labels could be move above similar to protoclusters
- detail tabs might be improved with a label for the distinct sections of tool information and area information

**Comment by SJShaw** [comment]
Updated and known issues resolved.

An extra command line option has been added `--sideloader-simple`, which can specify a single accession and area which will be marked as a `manual` tool. This is simplified as it is largely intended for debugging and the like rather than for real tool annotations.

Also changed is that `hmm_detection` now marks all profile hits in full regions which aren't covered by protoclusters it finds.

**Review by kblin — COMMENTED** [review]
Apart from this one JSON error, looks good.

**Review by kblin — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
