### PR TITLE
nrps_pks: Add PARAS, untested.

### PR DESCRIPTION
**Pull request by BTheDragonMaster**
Introduces PARAS A-domain predictions. Dos not yet include tests. Does not use PARAS predictions yet as consensus.

### CODE REVIEW

**Comment by SJShaw** [comment]
I know this is a draft, so I won't comment on but it seems like the non-antiSMASH portions of PARAS need some fixes.
This warning is repeated twice for every input, I remember discussing ways of handling it with you back in September.
```
lib/python3.9/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.24.2 when using version 1.1.3. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
```
Since the unpickle is happening for every domain, that's a lot of repetitive loads from disk. Does PARAS support a batch mode where it only has to load once for any given set of domains?

There's also some debug printing coming from PARAS that we don't want. The records I ran on crashed before reaching RAIChU, so I can't comment on that part.

Neither PARAS or RAIChU have a license, that's also something that we'd like to know about.

**Comment by SJShaw** [comment]
> Thanks for the feedback. Could you tell me 1. which records you ran RAIChU on and 2. which error messages you got, so that I can debug on my end (also useful for future PRs)?

The first was balhymicin (Y16952), which included as test data in antiSMASH. It's the same issue as every other input I tried, with variations of prediction substituted:
```
$ ./run_antismash.py antismash/test/integration/data/Y16952.gbk
 ...
 File "antismash/modules/nrps_pks/parsers.py", line 74, in generate_nrps_consensus
  raise ValueError("%s generated bad prediction string: %s" % (method, best))
ValueError: PARAS generated bad prediction string: "3,5-dihydroxyphenylglycine"
```

I assumed you were still working on that part, which is why I didn't go into detail about it.

**Comment by kblin** [comment]
This will be handled via the upcoming experimentalSMASH infrastructure for the time being, close for now.

**Comment by kblin** [comment]
Testing to see if I can get this to work with experimentalSMASH

**Comment by kblin** [comment]
Superseded by the PARAS outlink added in #761

**Pull request closed without merging**
